# Generated by Django 3.2.7 on 2021-09-07 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='favorite',
        ),
    ]
