# Generated by Django 3.2.7 on 2021-09-06 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20210906_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='favorite',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
